// src/pages/Home.jsx
import React, { useEffect, useState } from 'react'
import LoggedOutHeader from "../components/organism/logged-out-header";
import LoggedOutFooter from "../components/organism/logged-out-footer";
import LoggedOutLayout from "../components/organism/logged-out-layout";
import { HomePageHeroSection } from '../components/sections/HomePage/hero';
import { HomePageFeaturesSection } from '../components/sections/HomePage/features';
import { HomePageSummarySection } from '../components/sections/HomePage/summary';
import { HomePagePricingSection } from '../components/sections/HomePage/pricing';
import { HomePageFAQsSection } from '../components/sections/HomePage/faq';
import { HomePageCTASection } from '../components/sections/HomePage/cta';
import { MainSections } from '../components/molecule/main-sections';
import { TitleText } from '../components/molecule/title-text';
import { TextBlock } from '../components/molecule/text-blocks';

export default function TermsPage() {
    useEffect(() => {
        document.title = 'A11yScan — Automated Website Accessibility Scanning'
    }, [])

 


    return (
        <LoggedOutLayout>
            <LoggedOutHeader />

            <MainSections>
                <p className='as-p3-text secondary-text-color'><em>Last updated: 13/01/2026</em></p>
                <TitleText title={`Terms and Conditions`}/>
                <TextBlock title={`1. Purpose and Scope`}>
                    <p>These Terms and Conditions (“Terms”) govern access to and use of the Ablelytics platform (“Service”), operated by Ablelytics (“the Provider”).</p>
                    <p>The Service enables users to assess websites for potential accessibility issues through automated scanning and reporting tools.</p>
                    <p>By accessing or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms.</p>
                </TextBlock>

                <TextBlock title={`2. Definitions`}>
                    <ul>
                        <li>User: Any individual or organisation accessing the Service.</li>
                        <li>Account: A registered user profile required to access restricted features.</li>
                        <li>Report: Output generated by the Service identifying potential accessibility issues.</li>
                        <li>Website Under Test: A website scanned using the Service.</li>
                    </ul>
                </TextBlock>

                <TextBlock title={`3. Account Registration and Responsibilities`}>
                    <p>Use of the Service requires account registration.</p>
                    <p>The User is responsible for:</p>
                    <ul>
                        <li>Maintaining the confidentiality of access credentials</li>
                        <li>Ensuring information provided is accurate and current</li>
                        <li>All activity performed under their Account</li>
                    </ul>
                    <p>The Provider reserves the right to suspend or terminate Accounts that breach these Terms.</p>
                </TextBlock>

                <TextBlock title={`4. Permitted Use`}>
                    <p>Users must:</p>
                    <ul>
                        <li>Only scan websites they own or are authorised to assess</li>
                        <li>Use the Service in compliance with applicable laws and regulations</li>
                        <li>Not interfere with the operation, security, or integrity of the Service</li>
                    </ul>
                    <p>Unauthorised use may result in immediate suspension.</p>
                </TextBlock>

                <TextBlock title={`5. Accessibility Assessment Disclaimer`}>
                    <p>The Service provides automated accessibility assessments only.</p>
                    <p>Reports:</p>
                    <ul>
                        <li>Are indicative and non-exhaustive</li>
                        <li>Do not replace manual accessibility audits</li>
                        <li>Do not constitute legal advice or certification</li>
                    </ul>
                    <p>
                        The Provider makes no representation or warranty that use of the Service will result in legal compliance with accessibility legislation, including but not limited to WCAG, EN 301 549, or related standards.
                    </p>
                    <p>Responsibility for compliance remains with the User.</p>
                </TextBlock>
                <TextBlock title={`6. Fees and Payments`}>
                    <p>Certain features of the Service are subject to fees.</p>
                    <ul>
                        <li>Pricing is displayed prior to purchase</li>
                        <li>Payments are processed by a third-party payment provider</li>
                        <li>Subscriptions may renew automatically unless cancelled before the renewal date</li>
                    </ul>
                    <p>Refunds are not provided except where required by law.</p>
                </TextBlock>
                <TextBlock title={`7. Intellectual Property`}>
                    <p>
                        All intellectual property rights in the Service, including software, reports, documentation, and branding, remain the property of the Provider.
                    </p>
                    <p>
                        Users are granted a non-exclusive, non-transferable right to use reports internally for their own accessibility improvement activities.
                    </p>
                </TextBlock>
                <TextBlock title={`8. Service Availability and Modifications`}>
                    <p>The Provider does not guarantee uninterrupted availability of the Service.</p>
                    <p>
                        The Service, including functionality and pricing, may be modified or discontinued at any time.
                    </p>
                </TextBlock>
                <TextBlock title={`9. Limitation of Liability`}>
                    <p>To the maximum extent permitted by law, the Provider shall not be liable for:</p>
                    <ul>
                        <li>Indirect or consequential loss</li>
                        <li>Loss of business, revenue, or data</li>
                        <li>Outcomes related to accessibility compliance decisions</li>
                    </ul>
                </TextBlock>
                <TextBlock title={`10. Governing Law`}>
                    <p>
                        These Terms are governed by applicable European Union law and the local laws of the Provider’s jurisdiction.
                    </p>
                </TextBlock>
                <TextBlock title={`11. Contact`}>
                    <p>Email: support@ablelytics.com</p>
                    <p>Registered address: [TO BE ADDED]</p>
                </TextBlock>

            </MainSections>

            <LoggedOutFooter />
        </LoggedOutLayout>
    )
}